import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
        <Main />
        <NextScript>
          <script
            src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"
            crossorigin
          ></script>

          <script
            src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
            crossorigin
          ></script>

          <script
            src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
            crossorigin
          ></script>
        </NextScript>
      </body>
    </Html>
  );
}
